### ISSUE TITLE
Tika_deid not working since ES Upgrade

### ISSUE THREAD

**Issue by AMohabeer** [CogStack/CogStack-Pipeline#35]
Since upgrading ES to 5.4.2, the deid job gets stuck after "partitioning complete". See log attached.
[tika_deid_error.txt](https://github.com/CogStack/cogstack/files/1245207/tika_deid_error.txt)

Same thing happening with dbLineFixer job.

**Comment by AMohabeer** [comment]
Seems that by reducing the grid size, the job completes and records are indexed. This is strange as larger gird sizes worked previously (prior to the upgrade). I think this should still be investigated as I'm not sure how upgrading ES can cause this...?

**Comment by afolarin** [comment]
@AshaAgrawal is this resolved?

**Comment by AMohabeer** [comment]
@afolarin Partly yes. DBLineFixer is resolved but TikaAnonymised is still very slow. Honghan will be looking at this tomorrow after which we will update this thread.

**Comment by Honghan** [comment]
- the ES update did cause some issues on DBLinkeFixer: string type fields without analyzer will have a length limitation of their values (less than 32766). for details, please check this: https://github.com/CogStack/cogstack/commit/68cb059210c87140e1a8c924aec825e566ac9ea6.

- the deid slow indexing issue was caused by the view definition. it has been changed to a stored procedure, which seems much faster. Asha is doing final validation on this. If everything is fine, I think she will close this issue.

**Comment by afolarin** [comment]
@AshaAgrawal validation of this would be good. 
@Honghan if this is a general problem then can you update the docs

**Comment by AMohabeer** [comment]
As noted by Honghan, everything seems to be working fine, therefore closing issue.
